### ISSUE TITLE
The running experiment?

### ISSUE THREAD

**Issue by CHENJIAR3** [DebadityaQU/RDDM#3]
Dear authors, could you provide the running experiments? I really want the conda.sh.
Thank for your attention in advance.

**Comment by pritamqu** [comment]
@CHENJIAR3  do you mean dependencies to create a conda environment?
@DebadityaQU If so, could you please share a requirement.txt file of your environment...

**Comment by CHENJIAR3** [comment]
Thanks for your attention, and I have realized a conda enviroment. It is a really excellent research, and I am looking forward to follow your research.
