### ISSUE TITLE
Pre-process for original dataset

### ISSUE THREAD

**Issue by BugHunterCaiXuan** [DebadityaQU/RDDM#4]
In the course of my in-depth research, I found that my own transformed ‘ecg_train_{window_size}sec.npy’ data could not be fully adapted to the model input.  **Can you provide the code to generate the .npy file from the raw data file?** Thank you again for your consideration and support. I look forward to the opportunity to interact with you further and wish you much success in your academic research.

**Comment by chaliechu117** [comment]
Hi did you solve the problem? 
I also had a same issue. I tried to reproduce the result, but I couldn't reproduce the model output as the paper result. If you have solved the problem can you share how you solved the problem?

![plot_25](https://github.com/user-attachments/assets/609974a5-396e-41dc-98d2-a94b647cbc9a)
This graph is a result I reproduced the model with WESAD dataset. 
I hope for your response and thank you so much for reading my comment.
